shared:
  mailer_default_from_email: "'Todos' <notifications@todos.com>"
  support_email: support@todos.com
  mailer_delivery_method: :smtp
  mailer:
    smtp_settings:
      user_name: <%= ENV['AWS_SES_USERNAME'] %>
      password: <%= ENV['AWS_SES_PASSWORD'] %>
      address: email-smtp.us-east-1.amazonaws.com
      port: 587
      authentication: plain
  host: <%= ENV['APP_URL'] || ENV['HEROKU_APP_URL'] || 'http://localhost:3000' %>

test:
  mailer_delivery_method: :test
